package org.example.commands;

public enum CommandTypes {
    CREATE_DATABASE,
    CREATE_COLLECTION,
    CREATE_DOCUMENT,
    CREATE_INDEX,
    FIND,
    FIND_ALL,
    DELETE_DATABASE,
    DELETE_COLLECTION,
    DELETE_DOCUMENT,
    UPDATE_DOCUMENT,
    SYNC_UPDATE_DOCUMENT,
    ADD_USER,
    INITIALIZE,
    REDIRECT,
    SYNC,
    PING
}
